language: csharp
mono: latest
dotnet: 3.1.1
solution: API.sln
install:
  - nuget restore API.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release API.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Specification/bin/Release/Specification.dll