language: csharp
mono: latest
dotnet: 3.1.1
solution: API.sln
install:
  - nuget restore API.sln
  - nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release API.sln
  - dotnet test ./Specification/bin/Release/netcoreapp3.1/Specification.dll